name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        perl-version: [5.10, 5.40]

    name: Perl ${{ matrix.perl-version }} on ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install dependencies
        run: cpanm --notest --installdeps --verbose .

      - name: Run tests
        run: |
          perl Makefile.PL
          make
          make test

